<?php 

foreach ($EWS_COUNT_NEW_LIST as $EWS_COUNT_NEW_ROWS): 
    
    $EWS_COUNTED_NEW = $EWS_COUNT_NEW_ROWS['EWS_NEW'];
    $EWS_COUNTED_LAPSED = $EWS_COUNT_NEW_ROWS['EWS_LAPSED'];
    $EWS_COUNTED_CANCELLED_DD = $EWS_COUNT_NEW_ROWS['EWS_DD_CANCELLED'];
    $EWS_COUNTED_DD_REJECT = $EWS_COUNT_NEW_ROWS['EWS_DD_REJECT'];
    $EWS_COUNTED_CANCELLED = $EWS_COUNT_NEW_ROWS['EWS_CANCELLED'];
    $EWS_COUNTED_OUTSTANDING = $EWS_COUNT_NEW_ROWS['EWS_OUTSTANDING'];

endforeach;